import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useNavigate } from "@tanstack/react-router";
import { Check, ChevronLeft, ChevronRight, MessageSquare, Plus, Save, Send, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { TranscriptAnalyzer } from "@/components/transcript/TranscriptAnalyzer";
import { supabase } from "@/integrations/supabase/client";
import { useProfile } from "@/lib/auth";
import { todaySV } from "@/lib/date";
import { calculateStudent, normalizeAois, normalizeTextList, type AoiEntry, type MonitoringAnswer, type MonitoringItem, type ReportData, type StudentDraft } from "@/lib/monitoring";
import { fetchInternalReport } from "@/lib/monitoring-data";
import { computeBaseScore, computeFinalScore, expectationFor, phraseFor, type PhraseRule, type TemplateScoring } from "@/lib/scoring";
import type { Metrics } from "@/lib/transcript";
import { cn } from "@/lib/utils";
import { MonitoringReport } from "./MonitoringReport";
import { ScoreCircle } from "./ReportVisuals";

interface Config { bonus_points_each: number; penalty_cap: number; score_phrases: PhraseRule[]; expectation_phrases: PhraseRule[] }
interface Coach { id: string; full_name: string; lob: string | null; level: string | null; schedule: string | null }
interface Template { id: string; name: string; code: string; scoring: string | null; has_student_grid: boolean }
interface FormState { coach_id: string; template_id: string; class_date: string; qa_date: string; syllabus: string; schedule: string; level: string; zoom_link: string; previous_aois: string[]; kudos: string[]; aois: AoiEntry[]; general_comments: string; transcript_raw: string | null; transcript_metrics: Metrics | null }
const emptyStudent = (i: number): StudentDraft => ({ student_number: i + 1, student_name: "", gr: "", pr: "", fl: "", co: "", in: "", score: null, phrase: "", goal: false, coach_phrase: "", comment: "" });
const initial: FormState = { coach_id: "", template_id: "", class_date: todaySV(), qa_date: todaySV(), syllabus: "", schedule: "", level: "", zoom_link: "", previous_aois: [], kudos: [""], aois: [{ text: "", item_id: null }], general_comments: "", transcript_raw: null, transcript_metrics: null };

export function MonitoringWizard({ monitoringId }: { monitoringId?: string }) {
  const navigate = useNavigate();
  const { profile, canSeeAll } = useProfile();
  const [id, setId] = useState(monitoringId);
  const [step, setStep] = useState(1);
  const [form, setForm] = useState<FormState>(initial);
  const [answers, setAnswers] = useState<MonitoringAnswer[]>([]);
  const [students, setStudents] = useState<StudentDraft[]>(Array.from({ length: 4 }, (_, i) => emptyStudent(i)));
  const [commentsOpen, setCommentsOpen] = useState<Set<string>>(new Set());
  const [saving, setSaving] = useState(false);
  const loaded = useRef(false);

  const setup = useQuery({ queryKey: ["monitoring-setup"], queryFn: async () => {
    const [coaches, templates, items, config] = await Promise.all([
      supabase.from("coaches").select("id, full_name, lob, level, schedule").eq("active", true).order("full_name"),
      supabase.from("templates").select("id, name, code, scoring, has_student_grid").eq("active", true).order("sort_order"),
      supabase.from("template_items").select("*").order("sort_order", { nullsFirst: false }),
      supabase.from("app_config").select("key, value"),
    ]);
    for (const result of [coaches, templates, items, config]) if (result.error) throw result.error;
    const map = Object.fromEntries((config.data ?? []).map((x) => [x.key, x.value]));
    return { coaches: coaches.data as Coach[], templates: templates.data as Template[], items: items.data as MonitoringItem[], config: { bonus_points_each: Number(map.bonus_points_each ?? 0.25), penalty_cap: Number(map.penalty_cap ?? 5), score_phrases: (map.score_phrases ?? []) as unknown as PhraseRule[], expectation_phrases: (map.expectation_phrases ?? []) as unknown as PhraseRule[] } satisfies Config };
  }});

  useEffect(() => { if (!monitoringId || loaded.current) return; loaded.current = true; void (async () => {
    const { data: m, error } = await supabase.from("monitorings").select("*").eq("id", monitoringId).single(); if (error) return toast.error(error.message);
    const [{ data: aa }, { data: ss }] = await Promise.all([supabase.from("monitoring_answers").select("item_id,result,comment").eq("monitoring_id", monitoringId), supabase.from("monitoring_students").select("*").eq("monitoring_id", monitoringId).order("student_number")]);
    setForm({ coach_id: m.coach_id ?? "", template_id: m.template_id ?? "", class_date: m.class_date ?? todaySV(), qa_date: m.qa_date ?? todaySV(), syllabus: m.syllabus ?? "", schedule: m.schedule ?? "", level: m.level ?? "", zoom_link: m.zoom_link ?? "", previous_aois: normalizeTextList(m.previous_aois), kudos: normalizeTextList(m.kudos).length ? normalizeTextList(m.kudos) : [""], aois: normalizeAois(m.aois).length ? normalizeAois(m.aois) : [{ text: "", item_id: null }], general_comments: m.general_comments ?? "", transcript_raw: m.transcript_raw, transcript_metrics: m.transcript_metrics as unknown as Metrics | null });
    setAnswers((aa ?? []).filter((a) => a.item_id).map((a) => ({ item_id: a.item_id ?? "", result: a.result as MonitoringAnswer["result"], comment: a.comment ?? "" })));
    if (ss?.length) setStudents(ss.map((s) => ({ student_number: s.student_number ?? 1, student_name: s.student_name ?? "", gr: s.gr?.toString() ?? "", pr: s.pr?.toString() ?? "", fl: s.fl?.toString() ?? "", co: s.co?.toString() ?? "", in: s.in?.toString() ?? "", score: s.score, phrase: s.phrase ?? "", goal: Boolean(s.goal), coach_phrase: s.coach_phrase ?? "", comment: s.comment ?? "" })));
  })(); }, [monitoringId]);

  const selectedTemplate = setup.data?.templates.find((t) => t.id === form.template_id);
  const items = (setup.data?.items ?? []).filter((i) => i.template_id === form.template_id);
  const answerFor = (itemId: string) => answers.find((a) => a.item_id === itemId) ?? { item_id: itemId, result: "" as const, comment: "" };
  const scoredAnswers = answers.filter((a): a is MonitoringAnswer & { result: "si" | "no" | "na" } => a.result !== "");
  const config = setup.data?.config ?? { bonus_points_each: .25, penalty_cap: 5, score_phrases: [], expectation_phrases: [] };
  const base = computeBaseScore({ scoring: (selectedTemplate?.scoring ?? "points_sum") as TemplateScoring }, items, scoredAnswers);
  const bonusCount = items.filter((i) => i.kind === "bonus" && answerFor(i.id).result === "si").length;
  const penaltyCount = items.filter((i) => i.kind === "penalty" && answerFor(i.id).result === "si").length;
  const final = computeFinalScore(base, bonusCount, penaltyCount, config);
  const phrase = phraseFor(final, config.score_phrases);
  const expectation = expectationFor(final, config.expectation_phrases);
  const requiredItems = items.filter((i) => i.kind === "item" || i.kind === "checklist");
  const missing = requiredItems.filter((i) => !answerFor(i.id).result).length;

  const save = useCallback(async (quiet = false) => {
    if (!form.coach_id || !form.template_id) { if (!quiet) toast.error("Elige coach y tipo de monitoreo"); return null; }
    setSaving(true);
    try {
      const payload = { coach_id: form.coach_id, coordinator_id: profile.id, template_id: form.template_id, class_date: form.class_date || null, qa_date: form.qa_date, syllabus: form.syllabus || null, schedule: form.schedule || null, level: form.level || null, zoom_link: form.zoom_link || null, status: "borrador", previous_aois: form.previous_aois, kudos: form.kudos.filter(Boolean), aois: form.aois.filter((a) => a.text), main_aoi: form.aois[0]?.text || null, general_comments: form.general_comments || null, transcript_raw: form.transcript_raw, transcript_metrics: form.transcript_metrics as never, base_score: base, bonus_total: bonusCount * config.bonus_points_each, penalty_applied: penaltyCount > 0, final_score: final, result_phrase: phrase, customer_expectation: expectation };
      let monitoring = id;
      if (monitoring) { const { error } = await supabase.from("monitorings").update(payload).eq("id", monitoring); if (error) throw error; }
      else { const { data, error } = await supabase.from("monitorings").insert(payload).select("id").single(); if (error) throw error; monitoring = data.id; setId(data.id); }
      await Promise.all([supabase.from("monitoring_answers").delete().eq("monitoring_id", monitoring), supabase.from("monitoring_students").delete().eq("monitoring_id", monitoring)]);
      if (answers.some((a) => a.result)) { const { error } = await supabase.from("monitoring_answers").insert(answers.filter((a) => a.result).map((a) => ({ monitoring_id: monitoring as string, item_id: a.item_id, result: a.result, comment: a.comment || null }))); if (error) throw error; }
      const filled = students.filter((s) => s.student_name.trim());
      if (filled.length) { const { error } = await supabase.from("monitoring_students").insert(filled.map((s) => ({ monitoring_id: monitoring as string, student_number: s.student_number, student_name: s.student_name, gr: s.gr === "" ? null : Number(s.gr), pr: s.pr === "" ? null : Number(s.pr), fl: s.fl === "" ? null : Number(s.fl), co: s.co === "" ? null : Number(s.co), in: s.in === "" ? null : Number(s.in), score: s.score, phrase: s.phrase || null, goal: s.goal, coach_phrase: s.coach_phrase || null, comment: s.comment || null }))); if (error) throw error; }
      if (!quiet) toast.success("Borrador guardado"); return monitoring;
    } catch (error) { toast.error(error instanceof Error ? error.message : "No se pudo guardar"); return null; } finally { setSaving(false); }
  }, [answers, base, bonusCount, config, expectation, final, form, id, penaltyCount, phrase, profile.id, students]);

  useEffect(() => { const timer = window.setInterval(() => { if (id) void save(true); }, 20_000); return () => window.clearInterval(timer); }, [id, save]);
  async function go(next: number) { if (step === 1 && (!form.coach_id || !form.template_id)) return toast.error("Completa coach y tipo de monitoreo"); if (step === 2 && next > 2 && missing) return toast.error(`Faltan ${missing} respuestas`); await save(true); setStep(next); window.scrollTo({ top: 0, behavior: "smooth" }); }
  async function submit() { const monitoring = await save(true); if (!monitoring) return; const token = crypto.randomUUID(); const { error } = await supabase.from("monitorings").update({ status: "enviado", share_token: token, base_score: base, bonus_total: bonusCount * config.bonus_points_each, penalty_applied: penaltyCount > 0, final_score: final, result_phrase: phrase, customer_expectation: expectation }).eq("id", monitoring); if (error) return toast.error(error.message); toast.success("Monitoreo enviado"); navigate({ to: "/monitoreos/$id", params: { id: monitoring } }); }
  function chooseCoach(coachId: string) { const c = setup.data?.coaches.find((x) => x.id === coachId); setForm((f) => ({ ...f, coach_id: coachId, schedule: c?.schedule ?? "", level: c?.level ?? "" })); void supabase.from("monitorings").select("qa_date,aois,main_aoi").eq("coach_id", coachId).eq("status", "enviado").order("created_at", { ascending: false }).limit(1).maybeSingle().then(({ data }) => { const old = normalizeTextList(data?.aois); if (data?.main_aoi && !old.includes(data.main_aoi)) old.unshift(data.main_aoi); setForm((f) => ({ ...f, previous_aois: old })); }); }
  function setAnswer(itemId: string, result: MonitoringAnswer["result"]) { setAnswers((prev) => [...prev.filter((a) => a.item_id !== itemId), { ...answerFor(itemId), result }]); if (result === "no") setCommentsOpen((prev) => new Set(prev).add(itemId)); }
  function setComment(itemId: string, comment: string) { setAnswers((prev) => [...prev.filter((a) => a.item_id !== itemId), { ...answerFor(itemId), comment }]); }
  const publicReport = useQuery({ queryKey: ["wizard-preview", id, step], enabled: Boolean(id && step === 4), queryFn: () => fetchInternalReport(id ?? "") });

  return <div className="pb-24"><div className="sticky top-0 z-20 -mx-4 mb-6 border-b bg-background/95 px-4 py-3 backdrop-blur sm:-mx-6 sm:px-6 lg:top-0"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><div className="flex flex-1 gap-1">{["Datos", "Rúbrica", "Talking time", "Revisar"].map((label, i) => <div key={label} className="flex-1"><div className={cn("h-2 rounded-full", i + 1 <= step ? "bg-primary" : "bg-muted")} /><p className="mt-1 hidden text-xs sm:block">{i + 1}. {label}</p></div>)}</div><Button variant="outline" onClick={() => void save()} disabled={saving}><Save className="size-4" /> Guardar borrador</Button></div></div>
    {step === 1 ? <StepData form={form} setForm={setForm} coaches={(setup.data?.coaches ?? []).filter((c) => canSeeAll || true)} templates={setup.data?.templates ?? []} items={setup.data?.items ?? []} chooseCoach={chooseCoach} /> : null}
    {step === 2 ? <StepRubric form={form} setForm={setForm} template={selectedTemplate} items={items} answers={answers} answerFor={answerFor} setAnswer={setAnswer} setComment={setComment} commentsOpen={commentsOpen} setCommentsOpen={setCommentsOpen} students={students} setStudents={setStudents} base={base} final={final} phrase={phrase} expectation={expectation} bonus={bonusCount * config.bonus_points_each} penalty={penaltyCount > 0} config={config} /> : null}
    {step === 3 ? <section><h1 className="mb-5 text-2xl font-bold">Talking time</h1><TranscriptAnalyzer onMetrics={(metrics, raw) => setForm((f) => ({ ...f, transcript_metrics: metrics, transcript_raw: raw }))} /><div className="mt-4 flex justify-end"><Button variant="ghost" onClick={() => void go(4)}>Omitir (sin transcript)</Button></div></section> : null}
    {step === 4 ? <section><h1 className="mb-5 text-2xl font-bold">Así lo verá el coach</h1>{publicReport.data ? <MonitoringReport report={publicReport.data} /> : <div className="rounded-lg border p-8 text-center text-muted-foreground">Preparando vista previa…</div>}</section> : null}
    <div className="fixed inset-x-0 bottom-0 z-30 border-t bg-background/95 p-3 backdrop-blur lg:left-64"><div className="mx-auto flex max-w-6xl justify-between"><Button variant="outline" disabled={step === 1} onClick={() => void go(step - 1)}><ChevronLeft className="size-4" /> Volver</Button>{step < 4 ? <Button onClick={() => void go(step + 1)}>Continuar <ChevronRight className="size-4" /></Button> : <Button onClick={() => void submit()}><Send className="size-4" /> Enviar monitoreo</Button>}</div></div>
  </div>;
}

function StepData({ form, setForm, coaches, templates, items, chooseCoach }: { form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>>; coaches: Coach[]; templates: Template[]; items: MonitoringItem[]; chooseCoach: (id: string) => void }) {
  return <section className="space-y-6"><h1 className="text-2xl font-bold">Datos de la clase</h1><div className="grid gap-4 sm:grid-cols-2"><Field label="Coach"><Select value={form.coach_id} onValueChange={chooseCoach}><SelectTrigger><SelectValue placeholder="Buscar coach" /></SelectTrigger><SelectContent>{coaches.map((c) => <SelectItem key={c.id} value={c.id}>{c.full_name}</SelectItem>)}</SelectContent></Select></Field><Field label="Fecha de la clase"><Input type="date" value={form.class_date} onChange={(e) => setForm((f) => ({ ...f, class_date: e.target.value }))} /></Field><Field label="Fecha del QA"><Input type="date" value={form.qa_date} onChange={(e) => setForm((f) => ({ ...f, qa_date: e.target.value }))} /></Field><Field label="Nivel"><Input value={form.level} onChange={(e) => setForm((f) => ({ ...f, level: e.target.value }))} /></Field><Field label="Horario"><Input value={form.schedule} onChange={(e) => setForm((f) => ({ ...f, schedule: e.target.value }))} /></Field><Field label="Syllabus"><Input value={form.syllabus} onChange={(e) => setForm((f) => ({ ...f, syllabus: e.target.value }))} /></Field><Field label="Link de Zoom (opcional)"><Input value={form.zoom_link} onChange={(e) => setForm((f) => ({ ...f, zoom_link: e.target.value }))} /></Field></div><div><Label className="mb-3 block">Tipo de monitoreo</Label><div className="grid gap-3 sm:grid-cols-2">{templates.map((t) => { const related = items.filter((i) => i.template_id === t.id); return <button key={t.id} type="button" onClick={() => setForm((f) => ({ ...f, template_id: t.id }))} className={cn("rounded-lg border bg-card p-4 text-left transition", form.template_id === t.id ? "border-primary ring-2 ring-primary/20" : "hover:border-primary/40")}><div className="flex justify-between"><strong>{t.name}</strong><span className="rounded bg-muted px-2 py-0.5 text-xs">{t.code}</span></div><p className="mt-2 text-sm text-muted-foreground">{related.filter((i) => ["item", "checklist"].includes(i.kind ?? "")).length} ítems · {related.some((i) => i.kind === "penalty") ? "penalidades" : "sin penalidades"} · {t.has_student_grid ? "tabla de estudiantes" : "bonus"}</p></button>; })}</div></div>{form.previous_aois.length ? <div><Label>AOIs anteriores</Label><div className="mt-2 flex flex-wrap gap-2">{form.previous_aois.map((a) => <span key={a} className="rounded-full bg-muted px-3 py-1 text-sm">{a}</span>)}</div></div> : null}</section>;
}

function StepRubric(p: { form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>>; template?: Template; items: MonitoringItem[]; answers: MonitoringAnswer[]; answerFor: (id: string) => MonitoringAnswer; setAnswer: (id: string, result: MonitoringAnswer["result"]) => void; setComment: (id: string, value: string) => void; commentsOpen: Set<string>; setCommentsOpen: React.Dispatch<React.SetStateAction<Set<string>>>; students: StudentDraft[]; setStudents: React.Dispatch<React.SetStateAction<StudentDraft[]>>; base: number; final: number; phrase: string; expectation: string; bonus: number; penalty: boolean; config: Config }) {
  const groups = useMemo(() => { const map = new Map<string, MonitoringItem[]>(); for (const item of p.items.filter((i) => i.kind === "item" || i.kind === "checklist")) { const key = item.kind === "checklist" ? "Checklist" : [item.section, item.area].filter(Boolean).join(" · ") || "Rúbrica"; map.set(key, [...(map.get(key) ?? []), item]); } return Array.from(map.entries()); }, [p.items]);
  const noItems = p.items.filter((i) => p.answerFor(i.id).result === "no");
  return <section><div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_260px]"><div className="space-y-5"><h1 className="text-2xl font-bold">Rúbrica</h1>{groups.map(([name, list]) => <div key={name} className="rounded-lg border bg-card"><div className="border-b px-5 py-4 font-bold">{name}</div><div className="divide-y">{list.map((item) => { const a = p.answerFor(item.id); const transcriptHint = p.form.transcript_metrics && /(student talk time|equal participation|student-centered|equalized participation)/i.test(item.description); return <div key={item.id} className="p-4"><div className="flex gap-3"><span className="mt-0.5 text-xs font-bold text-muted-foreground">{item.item_number}</span><div className="min-w-0 flex-1"><p className="text-sm">{item.description}</p>{item.points != null && p.template?.scoring !== "area_weighted" ? <span className="mt-1 inline-block rounded bg-muted px-2 py-0.5 text-xs">{item.points} pt</span> : null}{transcriptHint ? <span className="mt-2 block rounded bg-primary/10 px-2 py-1 text-xs text-primary">Transcript: alumnos {p.form.transcript_metrics?.students_pct}% · {p.form.transcript_metrics?.students_below_min.length} bajo mínimo</span> : null}</div><div className="flex shrink-0 gap-1">{[["si", "Sí"], ["no", "No"], ["na", "N/A"]].map(([value, label]) => <Button key={value} type="button" size="sm" variant={a.result === value ? "default" : "outline"} className={cn(a.result === value && value === "si" && "bg-success", a.result === value && value === "no" && "bg-destructive")} onClick={() => p.setAnswer(item.id, value as MonitoringAnswer["result"])}>{label}</Button>)}<Button size="icon" variant="ghost" onClick={() => p.setCommentsOpen((old) => { const n = new Set(old); n.has(item.id) ? n.delete(item.id) : n.add(item.id); return n; })}><MessageSquare className="size-4" /></Button></div></div>{p.commentsOpen.has(item.id) ? <Textarea className={cn("mt-3", a.result === "no" && "border-warning")} placeholder="Comentario / evidencia (minuto de la clase)" value={a.comment} onChange={(e) => p.setComment(item.id, e.target.value)} /> : null}</div>; })}</div></div>)}
        {p.template?.has_student_grid ? <StudentGrid students={p.students} setStudents={p.setStudents} /> : null}
        {(["penalty", "bonus"] as const).map((kind) => { const list = p.items.filter((i) => i.kind === kind); if (!list.length) return null; return <div key={kind} className={cn("rounded-lg border p-5", kind === "penalty" ? "border-destructive/50" : "border-success/50")}><h2 className="font-bold">{kind === "penalty" ? `Needs to improve / Auto 5 · tope ${p.config.penalty_cap}` : `Bonus points (+${p.config.bonus_points_each} c/u)`}</h2>{list.map((item) => { const a = p.answerFor(item.id); return <div key={item.id} className="mt-4"><div className="flex items-center justify-between gap-4"><span className="text-sm">{item.description}</span><Switch checked={a.result === "si"} onCheckedChange={(v) => p.setAnswer(item.id, v ? "si" : "no")} /></div>{a.result === "si" ? <Textarea className="mt-2" placeholder="Comentario" value={a.comment} onChange={(e) => p.setComment(item.id, e.target.value)} /> : null}</div>; })}</div>; })}
        <FeedbackFields form={p.form} setForm={p.setForm} noItems={noItems} />
      </div><aside className="h-fit rounded-lg border bg-card p-5 shadow-panel lg:sticky lg:top-24"><p className="text-sm text-muted-foreground">Puntaje en vivo</p><div className="mt-4 flex justify-center"><ScoreCircle score={p.final} /></div><dl className="mt-5 space-y-2 text-sm"><div className="flex justify-between"><dt>Base</dt><dd className="font-bold">{p.base}</dd></div><div className="flex justify-between"><dt>Bonus</dt><dd className="font-bold text-success">+{p.bonus}</dd></div><div className="flex justify-between"><dt>Penalidad</dt><dd className="font-bold text-destructive">{p.penalty ? "Auto 5" : "—"}</dd></div></dl><p className="mt-4 text-center font-bold">{p.phrase || "—"}</p><p className="text-center text-xs text-muted-foreground">{p.expectation}</p></aside></div></section>;
}

function StudentGrid({ students, setStudents }: { students: StudentDraft[]; setStudents: React.Dispatch<React.SetStateAction<StudentDraft[]>> }) { const evaluated = students.filter((s) => s.student_name); const passing = evaluated.length ? Math.round(evaluated.filter((s) => s.goal).length / evaluated.length * 100) : 0; const calibration = evaluated.filter((s) => s.phrase && s.coach_phrase && s.phrase !== s.coach_phrase).length; function update(index: number, field: keyof StudentDraft, value: string | boolean) { setStudents((prev) => prev.map((s, i) => { if (i !== index) return s; const next = { ...s, [field]: value }; return { ...next, ...calculateStudent(next) }; })); } return <div className="rounded-lg border bg-card p-5"><h2 className="font-bold">Tabla de estudiantes</h2><div className="my-4 grid grid-cols-3 gap-2 text-center">{[["Evaluados", evaluated.length], ["Passing rate", `${passing}%`], ["Calibración", calibration]].map(([l, v]) => <div key={l} className="rounded bg-muted p-3"><strong className="block text-xl">{v}</strong><span className="text-xs">{l}</span></div>)}</div><div className="overflow-x-auto"><table className="min-w-[1100px] text-sm"><thead><tr>{["#", "Nombre", "GR", "PR", "FL", "CO", "IN", "Score", "Frase", "Goal", "Frase coach", "Comentario"].map((h) => <th key={h} className="p-2 text-left">{h}</th>)}</tr></thead><tbody>{students.map((s, i) => <tr key={s.student_number} className="border-t"><td>{i + 1}</td><td><Input className="w-36" value={s.student_name} onChange={(e) => update(i, "student_name", e.target.value)} /></td>{(["gr", "pr", "fl", "co", "in"] as const).map((f) => <td key={f}><Input className="w-16" type="number" min="0" max="10" value={s[f]} onChange={(e) => update(i, f, e.target.value)} /></td>)}<td className="font-bold">{s.score ?? "—"}</td><td className="w-28">{s.phrase}</td><td><Checkbox checked={s.goal} onCheckedChange={(v) => update(i, "goal", Boolean(v))} /></td><td><Input className="w-36" value={s.coach_phrase} onChange={(e) => update(i, "coach_phrase", e.target.value)} /></td><td><Input className="w-40" value={s.comment} onChange={(e) => update(i, "comment", e.target.value)} /></td></tr>)}</tbody></table></div>{students.length < 12 ? <Button className="mt-3" variant="outline" onClick={() => setStudents((s) => [...s, emptyStudent(s.length)])}><Plus className="size-4" /> Agregar alumno</Button> : null}</div>; }

function FeedbackFields({ form, setForm, noItems }: { form: FormState; setForm: React.Dispatch<React.SetStateAction<FormState>>; noItems: MonitoringItem[] }) { function list(kind: "kudos" | "aois") { const values = form[kind]; return <div className="space-y-2"><h2 className="font-bold">{kind === "kudos" ? "🟢 Kudos" : "🎯 AOIs"}</h2>{values.map((entry, i) => { const text = typeof entry === "string" ? entry : entry.text; return <div key={i} className="flex gap-2"><div className="flex-1"><Input placeholder={i === 0 ? (kind === "kudos" ? "Kudo principal" : "AOI principal") : "Agregar otro"} value={text} onChange={(e) => setForm((f) => ({ ...f, [kind]: kind === "kudos" ? f.kudos.map((x, xIndex) => xIndex === i ? e.target.value : x) : f.aois.map((x, xIndex) => xIndex === i ? { ...x, text: e.target.value } : x) }))} />{kind === "aois" && noItems.length ? <Select value={(entry as AoiEntry).item_id ?? "none"} onValueChange={(v) => setForm((f) => ({ ...f, aois: f.aois.map((x, xIndex) => xIndex === i ? { ...x, item_id: v === "none" ? null : v } : x) }))}><SelectTrigger className="mt-1"><SelectValue placeholder="Ítem relacionado" /></SelectTrigger><SelectContent><SelectItem value="none">Sin ítem</SelectItem>{noItems.map((item) => <SelectItem key={item.id} value={item.id}>{item.item_number} {item.short_label || item.description}</SelectItem>)}</SelectContent></Select> : null}</div><Button size="icon" variant="ghost" onClick={() => setForm((f) => ({ ...f, [kind]: values.filter((_, x) => x !== i) }))}><Trash2 className="size-4" /></Button></div>; })}{values.length < 10 ? <Button variant="outline" size="sm" onClick={() => setForm((f) => ({ ...f, [kind]: kind === "kudos" ? [...f.kudos, ""] : [...f.aois, { text: "", item_id: null }] }))}><Plus className="size-4" /> Agregar</Button> : null}</div>; } return <div className="space-y-5 rounded-lg border bg-card p-5"><div className="grid gap-5 md:grid-cols-2">{list("kudos")}{list("aois")}</div><Field label="Comentarios generales"><Textarea value={form.general_comments} onChange={(e) => setForm((f) => ({ ...f, general_comments: e.target.value }))} /></Field></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }