import { useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ClipboardPlus, Target, TrendingUp } from "lucide-react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/supabase/client";
import { countNormalizedAois } from "@/lib/monitoring";
import { formatDateSV, monthStartSV, nextMonthStartSV } from "@/lib/date";

export const Route = createFileRoute("/_authenticated/coaches/$coachId")({ head: () => ({ meta: [{ title: "Perfil del coach · QA Coaches E4K" }, { name: "description", content: "Tendencia, historial y áreas de enfoque del coach." }, { property: "og:title", content: "Perfil del coach · QA Coaches E4K" }, { property: "og:description", content: "Tendencia e historial de calidad." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: CoachProfile });

function CoachProfile() {
  const { coachId } = Route.useParams();
  const query = useQuery({ queryKey: ["coach-profile", coachId], queryFn: async () => { const [coach, monitorings] = await Promise.all([supabase.from("coaches").select("*").eq("id", coachId).single(), supabase.from("monitorings").select("id,class_date,qa_date,final_score,result_phrase,aois,main_aoi,coach_commitment,coach_responded_at,template:templates(name)").eq("coach_id", coachId).eq("status", "enviado").order("class_date", { ascending: false }).limit(50)]); if (coach.error) throw coach.error; if (monitorings.error) throw monitorings.error; const ids = (monitorings.data ?? []).map((m) => m.id); const answers = ids.length ? await supabase.from("monitoring_answers").select("monitoring_id,result,item:template_items(description)").in("monitoring_id", ids).eq("result", "no") : { data: [], error: null }; if (answers.error) throw answers.error; return { coach: coach.data, monitorings: monitorings.data ?? [], answers: answers.data ?? [] }; } });
  const stats = useMemo(() => { const list = query.data?.monitorings ?? []; const scores = list.flatMap((m) => m.final_score == null ? [] : [Number(m.final_score)]); const month = list.filter((m) => (m.qa_date ?? "") >= monthStartSV() && (m.qa_date ?? "") < nextMonthStartSV()); const items = new Map<string, number>(); for (const a of query.data?.answers ?? []) { const text = a.item?.description; if (text) items.set(text, (items.get(text) ?? 0) + 1); } return { average: scores.length ? scores.reduce((a, b) => a + b, 0) / scores.length : null, month: month.length, aois: countNormalizedAois(list.map((m) => m.aois)).slice(0, 5), items: [...items.entries()].sort((a, b) => b[1] - a[1]).slice(0, 5), trend: list.slice(0, 12).reverse().map((m) => ({ date: formatDateSV(m.class_date), score: m.final_score })) }; }, [query.data]);
  if (query.isLoading) return <p className="text-sm text-muted-foreground">Cargando perfil…</p>; if (!query.data) return <p>No se encontró el coach.</p>; const { coach, monitorings } = query.data;
  return <><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Button asChild variant="ghost"><Link to="/coaches"><ArrowLeft className="size-4" /> Mis coaches</Link></Button><Button asChild><Link to="/monitoreos/nuevo" search={{ coachId }}><ClipboardPlus className="size-4" /> Nuevo monitoreo</Link></Button></div><header className="border-b pb-6"><h1 className="text-3xl font-bold">{coach.full_name}</h1><p className="mt-2 text-muted-foreground">{[coach.lob, coach.level, coach.schedule].filter(Boolean).join(" · ") || "Sin datos de clase"}</p></header><div className="my-6 grid gap-3 sm:grid-cols-3"><Kpi label="Promedio" value={stats.average?.toFixed(1) ?? "—"} /><Kpi label="Este mes" value={String(stats.month)} /><Kpi label="Total" value={String(monitorings.length)} /></div><div className="grid gap-6 lg:grid-cols-[2fr_1fr]"><section className="rounded-lg border bg-card p-5"><h2 className="flex items-center gap-2 font-bold"><TrendingUp className="size-5 text-primary" /> Tendencia</h2><div className="mt-4 h-56">{stats.trend.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={stats.trend}><XAxis dataKey="date" fontSize={10} /><YAxis domain={[0, 10]} /><Tooltip /><Line type="monotone" dataKey="score" stroke="var(--primary)" strokeWidth={3} dot /></LineChart></ResponsiveContainer> : <p className="text-sm text-muted-foreground">Sin resultados todavía.</p>}</div></section><section className="rounded-lg border bg-card p-5"><h2 className="flex items-center gap-2 font-bold"><Target className="size-5 text-warning" /> AOIs recurrentes</h2><div className="mt-4 space-y-2">{stats.aois.map((a) => <div key={a.name} className="flex justify-between gap-3 text-sm"><span>{a.name}</span><Badge variant="outline">{a.count}</Badge></div>)}</div><h3 className="mt-6 text-sm font-bold">Ítems más fallados</h3><div className="mt-3 space-y-2">{stats.items.map(([name, count]) => <div key={name} className="flex justify-between gap-3 text-xs"><span>{name}</span><strong>{count}</strong></div>)}</div></section></div><section className="mt-6 overflow-x-auto rounded-lg border bg-card"><table className="w-full text-sm"><thead className="bg-muted"><tr><th className="p-3 text-left">Fecha</th><th className="p-3 text-left">Tipo</th><th className="p-3">Puntaje</th><th className="p-3 text-left">AOI principal</th><th className="p-3 text-left">Respuesta</th></tr></thead><tbody>{monitorings.map((m) => <tr key={m.id} className="border-t"><td className="p-3"><Link to="/monitoreos/$id" params={{ id: m.id }} className="font-semibold text-primary">{formatDateSV(m.class_date)}</Link></td><td className="p-3">{m.template?.name}</td><td className="p-3 text-center text-lg font-bold">{m.final_score?.toFixed(1) ?? "—"}</td><td className="p-3">{m.main_aoi || "—"}</td><td className="p-3">{m.coach_responded_at ? "Recibida" : "Pendiente"}</td></tr>)}</tbody></table></section></>;
}
function Kpi({ label, value }: { label: string; value: string }) { return <div className="rounded-lg border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>; }