/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAnalizadorRouteImport } from './routes/_authenticated/analizador'
import { Route as AuthenticatedCoachesRouteImport } from './routes/_authenticated/coaches'
import { Route as AuthenticatedConfiguracionRouteImport } from './routes/_authenticated/configuracion'
import { Route as AuthenticatedMesRouteImport } from './routes/_authenticated/mes'
import { Route as BTokenRouteImport } from './routes/b.$token'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AuthenticatedBettyIndexRouteImport } from './routes/_authenticated/betty.index'
import { Route as AuthenticatedBettyIdRouteImport } from './routes/_authenticated/betty.$id'
import { Route as AuthenticatedBettyCalibracionRouteImport } from './routes/_authenticated/betty.calibracion'
import { Route as AuthenticatedBettyNuevoRouteImport } from './routes/_authenticated/betty.nuevo'
import { Route as AuthenticatedCoachesCoachIdRouteImport } from './routes/_authenticated/coaches.$coachId'
import { Route as AuthenticatedMonitoreosIndexRouteImport } from './routes/_authenticated/monitoreos.index'
import { Route as AuthenticatedMonitoreosIdRouteImport } from './routes/_authenticated/monitoreos.$id'
import { Route as AuthenticatedMonitoreosNuevoRouteImport } from './routes/_authenticated/monitoreos.nuevo'
import { Route as AuthenticatedPlantillasIndexRouteImport } from './routes/_authenticated/plantillas.index'
import { Route as AuthenticatedPlantillasTemplateIdRouteImport } from './routes/_authenticated/plantillas.$templateId'
import { Route as AuthenticatedAdminUsersImportRouteImport } from './routes/_authenticated/admin.users.import'
import { Route as AuthenticatedMonitoreosIdEditarRouteImport } from './routes/_authenticated/monitoreos_.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalizadorRoute = AuthenticatedAnalizadorRouteImport.update({
  id: '/analizador',
  path: '/analizador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachesRoute = AuthenticatedCoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracionRoute =
  AuthenticatedConfiguracionRouteImport.update({
    id: '/configuracion',
    path: '/configuracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMesRoute = AuthenticatedMesRouteImport.update({
  id: '/mes',
  path: '/mes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BTokenRoute = BTokenRouteImport.update({
  id: '/b/$token',
  path: '/b/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBettyIndexRoute = AuthenticatedBettyIndexRouteImport.update({
  id: '/betty/',
  path: '/betty/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBettyIdRoute = AuthenticatedBettyIdRouteImport.update({
  id: '/betty/$id',
  path: '/betty/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBettyCalibracionRoute =
  AuthenticatedBettyCalibracionRouteImport.update({
    id: '/betty/calibracion',
    path: '/betty/calibracion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBettyNuevoRoute = AuthenticatedBettyNuevoRouteImport.update({
  id: '/betty/nuevo',
  path: '/betty/nuevo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachesCoachIdRoute =
  AuthenticatedCoachesCoachIdRouteImport.update({
    id: '/$coachId',
    path: '/$coachId',
    getParentRoute: () => AuthenticatedCoachesRoute,
  } as any)
const AuthenticatedMonitoreosIndexRoute =
  AuthenticatedMonitoreosIndexRouteImport.update({
    id: '/monitoreos/',
    path: '/monitoreos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoreosIdRoute =
  AuthenticatedMonitoreosIdRouteImport.update({
    id: '/monitoreos/$id',
    path: '/monitoreos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoreosNuevoRoute =
  AuthenticatedMonitoreosNuevoRouteImport.update({
    id: '/monitoreos/nuevo',
    path: '/monitoreos/nuevo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlantillasIndexRoute =
  AuthenticatedPlantillasIndexRouteImport.update({
    id: '/plantillas/',
    path: '/plantillas/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlantillasTemplateIdRoute =
  AuthenticatedPlantillasTemplateIdRouteImport.update({
    id: '/plantillas/$templateId',
    path: '/plantillas/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersImportRoute =
  AuthenticatedAdminUsersImportRouteImport.update({
    id: '/admin/users/import',
    path: '/admin/users/import',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonitoreosIdEditarRoute =
  AuthenticatedMonitoreosIdEditarRouteImport.update({
    id: '/monitoreos_/$id/editar',
    path: '/monitoreos/$id/editar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analizador': typeof AuthenticatedAnalizadorRoute
  '/coaches': typeof AuthenticatedCoachesRouteWithChildren
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/mes': typeof AuthenticatedMesRoute
  '/b/$token': typeof BTokenRoute
  '/r/$token': typeof RTokenRoute
  '/betty/$id': typeof AuthenticatedBettyIdRoute
  '/betty/calibracion': typeof AuthenticatedBettyCalibracionRoute
  '/betty/nuevo': typeof AuthenticatedBettyNuevoRoute
  '/coaches/$coachId': typeof AuthenticatedCoachesCoachIdRoute
  '/monitoreos/$id': typeof AuthenticatedMonitoreosIdRoute
  '/monitoreos/nuevo': typeof AuthenticatedMonitoreosNuevoRoute
  '/plantillas/$templateId': typeof AuthenticatedPlantillasTemplateIdRoute
  '/betty/': typeof AuthenticatedBettyIndexRoute
  '/monitoreos/': typeof AuthenticatedMonitoreosIndexRoute
  '/plantillas/': typeof AuthenticatedPlantillasIndexRoute
  '/admin/users/import': typeof AuthenticatedAdminUsersImportRoute
  '/monitoreos/$id/editar': typeof AuthenticatedMonitoreosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/analizador': typeof AuthenticatedAnalizadorRoute
  '/coaches': typeof AuthenticatedCoachesRouteWithChildren
  '/configuracion': typeof AuthenticatedConfiguracionRoute
  '/mes': typeof AuthenticatedMesRoute
  '/b/$token': typeof BTokenRoute
  '/r/$token': typeof RTokenRoute
  '/betty/$id': typeof AuthenticatedBettyIdRoute
  '/betty/calibracion': typeof AuthenticatedBettyCalibracionRoute
  '/betty/nuevo': typeof AuthenticatedBettyNuevoRoute
  '/coaches/$coachId': typeof AuthenticatedCoachesCoachIdRoute
  '/monitoreos/$id': typeof AuthenticatedMonitoreosIdRoute
  '/monitoreos/nuevo': typeof AuthenticatedMonitoreosNuevoRoute
  '/plantillas/$templateId': typeof AuthenticatedPlantillasTemplateIdRoute
  '/betty': typeof AuthenticatedBettyIndexRoute
  '/monitoreos': typeof AuthenticatedMonitoreosIndexRoute
  '/plantillas': typeof AuthenticatedPlantillasIndexRoute
  '/admin/users/import': typeof AuthenticatedAdminUsersImportRoute
  '/monitoreos/$id/editar': typeof AuthenticatedMonitoreosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/analizador': typeof AuthenticatedAnalizadorRoute
  '/_authenticated/coaches': typeof AuthenticatedCoachesRouteWithChildren
  '/_authenticated/configuracion': typeof AuthenticatedConfiguracionRoute
  '/_authenticated/mes': typeof AuthenticatedMesRoute
  '/b/$token': typeof BTokenRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/betty/$id': typeof AuthenticatedBettyIdRoute
  '/_authenticated/betty/calibracion': typeof AuthenticatedBettyCalibracionRoute
  '/_authenticated/betty/nuevo': typeof AuthenticatedBettyNuevoRoute
  '/_authenticated/coaches/$coachId': typeof AuthenticatedCoachesCoachIdRoute
  '/_authenticated/monitoreos/$id': typeof AuthenticatedMonitoreosIdRoute
  '/_authenticated/monitoreos/nuevo': typeof AuthenticatedMonitoreosNuevoRoute
  '/_authenticated/plantillas/$templateId': typeof AuthenticatedPlantillasTemplateIdRoute
  '/_authenticated/betty/': typeof AuthenticatedBettyIndexRoute
  '/_authenticated/monitoreos/': typeof AuthenticatedMonitoreosIndexRoute
  '/_authenticated/plantillas/': typeof AuthenticatedPlantillasIndexRoute
  '/_authenticated/admin/users/import': typeof AuthenticatedAdminUsersImportRoute
  '/_authenticated/monitoreos_/$id/editar': typeof AuthenticatedMonitoreosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analizador'
    | '/coaches'
    | '/configuracion'
    | '/mes'
    | '/b/$token'
    | '/r/$token'
    | '/betty/$id'
    | '/betty/calibracion'
    | '/betty/nuevo'
    | '/coaches/$coachId'
    | '/monitoreos/$id'
    | '/monitoreos/nuevo'
    | '/plantillas/$templateId'
    | '/betty/'
    | '/monitoreos/'
    | '/plantillas/'
    | '/admin/users/import'
    | '/monitoreos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analizador'
    | '/coaches'
    | '/configuracion'
    | '/mes'
    | '/b/$token'
    | '/r/$token'
    | '/betty/$id'
    | '/betty/calibracion'
    | '/betty/nuevo'
    | '/coaches/$coachId'
    | '/monitoreos/$id'
    | '/monitoreos/nuevo'
    | '/plantillas/$templateId'
    | '/betty'
    | '/monitoreos'
    | '/plantillas'
    | '/admin/users/import'
    | '/monitoreos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/analizador'
    | '/_authenticated/coaches'
    | '/_authenticated/configuracion'
    | '/_authenticated/mes'
    | '/b/$token'
    | '/r/$token'
    | '/_authenticated/betty/$id'
    | '/_authenticated/betty/calibracion'
    | '/_authenticated/betty/nuevo'
    | '/_authenticated/coaches/$coachId'
    | '/_authenticated/monitoreos/$id'
    | '/_authenticated/monitoreos/nuevo'
    | '/_authenticated/plantillas/$templateId'
    | '/_authenticated/betty/'
    | '/_authenticated/monitoreos/'
    | '/_authenticated/plantillas/'
    | '/_authenticated/admin/users/import'
    | '/_authenticated/monitoreos_/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  BTokenRoute: typeof BTokenRoute
  RTokenRoute: typeof RTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analizador': {
      id: '/_authenticated/analizador'
      path: '/analizador'
      fullPath: '/analizador'
      preLoaderRoute: typeof AuthenticatedAnalizadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches': {
      id: '/_authenticated/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof AuthenticatedCoachesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracion': {
      id: '/_authenticated/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AuthenticatedConfiguracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mes': {
      id: '/_authenticated/mes'
      path: '/mes'
      fullPath: '/mes'
      preLoaderRoute: typeof AuthenticatedMesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/b/$token': {
      id: '/b/$token'
      path: '/b/$token'
      fullPath: '/b/$token'
      preLoaderRoute: typeof BTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/betty/': {
      id: '/_authenticated/betty/'
      path: '/betty'
      fullPath: '/betty/'
      preLoaderRoute: typeof AuthenticatedBettyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/betty/$id': {
      id: '/_authenticated/betty/$id'
      path: '/betty/$id'
      fullPath: '/betty/$id'
      preLoaderRoute: typeof AuthenticatedBettyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/betty/calibracion': {
      id: '/_authenticated/betty/calibracion'
      path: '/betty/calibracion'
      fullPath: '/betty/calibracion'
      preLoaderRoute: typeof AuthenticatedBettyCalibracionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/betty/nuevo': {
      id: '/_authenticated/betty/nuevo'
      path: '/betty/nuevo'
      fullPath: '/betty/nuevo'
      preLoaderRoute: typeof AuthenticatedBettyNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coaches/$coachId': {
      id: '/_authenticated/coaches/$coachId'
      path: '/$coachId'
      fullPath: '/coaches/$coachId'
      preLoaderRoute: typeof AuthenticatedCoachesCoachIdRouteImport
      parentRoute: typeof AuthenticatedCoachesRoute
    }
    '/_authenticated/monitoreos/': {
      id: '/_authenticated/monitoreos/'
      path: '/monitoreos'
      fullPath: '/monitoreos/'
      preLoaderRoute: typeof AuthenticatedMonitoreosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoreos/$id': {
      id: '/_authenticated/monitoreos/$id'
      path: '/monitoreos/$id'
      fullPath: '/monitoreos/$id'
      preLoaderRoute: typeof AuthenticatedMonitoreosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoreos/nuevo': {
      id: '/_authenticated/monitoreos/nuevo'
      path: '/monitoreos/nuevo'
      fullPath: '/monitoreos/nuevo'
      preLoaderRoute: typeof AuthenticatedMonitoreosNuevoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantillas/': {
      id: '/_authenticated/plantillas/'
      path: '/plantillas'
      fullPath: '/plantillas/'
      preLoaderRoute: typeof AuthenticatedPlantillasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plantillas/$templateId': {
      id: '/_authenticated/plantillas/$templateId'
      path: '/plantillas/$templateId'
      fullPath: '/plantillas/$templateId'
      preLoaderRoute: typeof AuthenticatedPlantillasTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users/import': {
      id: '/_authenticated/admin/users/import'
      path: '/admin/users/import'
      fullPath: '/admin/users/import'
      preLoaderRoute: typeof AuthenticatedAdminUsersImportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoreos_/$id/editar': {
      id: '/_authenticated/monitoreos_/$id/editar'
      path: '/monitoreos/$id/editar'
      fullPath: '/monitoreos/$id/editar'
      preLoaderRoute: typeof AuthenticatedMonitoreosIdEditarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCoachesRouteChildren {
  AuthenticatedCoachesCoachIdRoute: typeof AuthenticatedCoachesCoachIdRoute
}

const AuthenticatedCoachesRouteChildren: AuthenticatedCoachesRouteChildren = {
  AuthenticatedCoachesCoachIdRoute: AuthenticatedCoachesCoachIdRoute,
}

const AuthenticatedCoachesRouteWithChildren =
  AuthenticatedCoachesRoute._addFileChildren(AuthenticatedCoachesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalizadorRoute: typeof AuthenticatedAnalizadorRoute
  AuthenticatedCoachesRoute: typeof AuthenticatedCoachesRouteWithChildren
  AuthenticatedConfiguracionRoute: typeof AuthenticatedConfiguracionRoute
  AuthenticatedMesRoute: typeof AuthenticatedMesRoute
  AuthenticatedBettyIdRoute: typeof AuthenticatedBettyIdRoute
  AuthenticatedBettyCalibracionRoute: typeof AuthenticatedBettyCalibracionRoute
  AuthenticatedBettyNuevoRoute: typeof AuthenticatedBettyNuevoRoute
  AuthenticatedMonitoreosIdRoute: typeof AuthenticatedMonitoreosIdRoute
  AuthenticatedMonitoreosNuevoRoute: typeof AuthenticatedMonitoreosNuevoRoute
  AuthenticatedPlantillasTemplateIdRoute: typeof AuthenticatedPlantillasTemplateIdRoute
  AuthenticatedBettyIndexRoute: typeof AuthenticatedBettyIndexRoute
  AuthenticatedMonitoreosIndexRoute: typeof AuthenticatedMonitoreosIndexRoute
  AuthenticatedPlantillasIndexRoute: typeof AuthenticatedPlantillasIndexRoute
  AuthenticatedAdminUsersImportRoute: typeof AuthenticatedAdminUsersImportRoute
  AuthenticatedMonitoreosIdEditarRoute: typeof AuthenticatedMonitoreosIdEditarRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalizadorRoute: AuthenticatedAnalizadorRoute,
  AuthenticatedCoachesRoute: AuthenticatedCoachesRouteWithChildren,
  AuthenticatedConfiguracionRoute: AuthenticatedConfiguracionRoute,
  AuthenticatedMesRoute: AuthenticatedMesRoute,
  AuthenticatedBettyIdRoute: AuthenticatedBettyIdRoute,
  AuthenticatedBettyCalibracionRoute: AuthenticatedBettyCalibracionRoute,
  AuthenticatedBettyNuevoRoute: AuthenticatedBettyNuevoRoute,
  AuthenticatedMonitoreosIdRoute: AuthenticatedMonitoreosIdRoute,
  AuthenticatedMonitoreosNuevoRoute: AuthenticatedMonitoreosNuevoRoute,
  AuthenticatedPlantillasTemplateIdRoute:
    AuthenticatedPlantillasTemplateIdRoute,
  AuthenticatedBettyIndexRoute: AuthenticatedBettyIndexRoute,
  AuthenticatedMonitoreosIndexRoute: AuthenticatedMonitoreosIndexRoute,
  AuthenticatedPlantillasIndexRoute: AuthenticatedPlantillasIndexRoute,
  AuthenticatedAdminUsersImportRoute: AuthenticatedAdminUsersImportRoute,
  AuthenticatedMonitoreosIdEditarRoute: AuthenticatedMonitoreosIdEditarRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  BTokenRoute: BTokenRoute,
  RTokenRoute: RTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
